### ISSUE TITLE
Strange Data Readings

### ISSUE THREAD

**Issue by alnbk5** [SingleTact/StandaloneArduino#1]
I am currently connecting my SingleTact sensor to an Arduino Uno and then transferring data to my computer via serial connection.

When I use the code as is, I get numbers displayed starting at 256 and up. It seems like something weird is happening with the rawData bit shift.

`short rawData = (incomingI2CBuffer[4] << 8) + incomingI2CBuffer[5]; //get the raw data`

When I display the MSB and LSB individually, I get even weirder results. 

- The MSB displays 0 without force or 1 when force is applied. 

- The LSB fluctuates in the 200's without force and then seems to read correctly when force is applied. 

Any idea what's going on?

**Comment by alnbk5** [comment]
Received the following email from SingleTact after asking why the readings started at 256 and up.

> Thank you for your email. 
> 
> It is just an offset, subtract 256 from all readings.
> 
> Sensor outputs 10 bit = 1024 counts.
> We typically subtract 255 as this is the negative region.  We do this so we don't truncate at 0 in the negative direction.
> 255 to 768 is the full scale range (or 0-512 if you subtract the offset)
> 768 to 1024 is over pressure (or 512 - 768 if you subtract the offset)
> 
> Please let me know if you need further information.

Fixed the issue by changing the rawData line to the following:

`short rawData = (incomingI2CBuffer[4] << 8) + incomingI2CBuffer[5] - 256; //get the raw data`

**Comment by martyngpps** [comment]
Hi,

Section2.4.3 of the user manual explains that "The functional sensor FSR
output range is 9-bits from x0100 to 0x2FF, corresponding to the 0.5V to
1.5V analog output range. The larger 10-bit total range allows for
detection of negative values when the sensor is under tension and some
level of over pressure detection." which is completely in line with the
unloaded 256 value.

regards,

Martyn Gallop

Senior Electronics Engineer
PPS
Tel: +44 (0)1415597150
Email: martyn.gallop@pressureprofile.com

Registered Office:
Inovo, Suite-H.
121 George St.
Glasgow
G1 1RD
Registration Number: SC509380
VAT Number: 225278605
