### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [SingleTact/StandaloneArduino#3]
When the Wire.requestFrom() returns, the transaction on the I2C bus has completely finished and the received data is waiting in a buffer. There is no need to wait for something after the Wire.requestFrom().

The return value of Wire.requestFrom() could be checked or Wire.available() could be checked if the same amount of bytes was received as was requested. If that was succesful, a for-loop can be used to retrieve the data, or the function Wire.readBytes() or a while-loop with Wire.available().

The waiting with a delay is in "StandaloneArduino/SingleTactDemo.ino" and "StandaloneArduino/SingleTactMultiSensorDemo.ino" and in an other repository: "ExampleArduinoInterface/SingleTactDemo.ino".

**Comment by dayizhang** [comment]
There is no wait after Wire.requestFrom() in our application. We checked Wire.available() and if it returns unsuccessful, we wait microseconds.

**Comment by Koepel** [comment]
Yes, and that is not correct.

The code waits microseconds if the Wire.available() returns zero. But that is in a while-loop. The delayMicroseconds(10) could be called over and over again. That delay is not needed, and it can do harm.

When the Wire.requestFrom() returns, no more data will be added to the buffer in the Wire library. The Wire.available() returns the number of bytes in the buffer and will never increase. It will decrease when a byte is read from the buffer with Wire.read().

If the Wire library is able to detect a problem on the I2C bus, the Wire.requestFrom() might return with no data in the buffer and the Wire.available() returns zero. In that case code will be stuck in the while-loop.

That means that when the delayMicroseconds(10) is called once, the code is already stuck in the while-loop and the sketch will not continue.

If I did not explain it properly, just ask.

**Comment by Koepel** [comment]
Could you please reconsider this ?  
I have made a wiki to describe the usage of the Wire library: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by Koepel** [comment]
The while-loop with the delay is still in the files "SingleTactDemo.ino" and "SingleTactMultiSensorDemo.ino".

The `Wire.requestFrom()` is blocking. When it returns, the I2C transaction on the bus has completely finished and the data is in a buffer (in the Wire library). The `Wire.available()` and `Wire.read()` operate only on that buffer.
