### ISSUE TITLE
Data Readings to Force value  or  to Volt value

### ISSUE THREAD

**Issue by Aliaiman** [SingleTact/StandaloneArduino#4]
hey, 

How can i convert the Sensor Data Readings like (256) to 0,5V  automatic or to Force  with Arduino ???

thanks

**Comment by malcpps** [comment]
This area is for reporting bugs or requesting features.

To ask a question, please use the [Forum](https://www.singletact.com/forums/topic/forum/).

PS Sections 2.5 and 2.6 of the [Manual](https://www.singletact.com/SingleTact_Manual.pdf) might help you.
