### ISSUE TITLE
Error 3 on end of Transmission (NACK on end of data) when implemented with multiplexer

### ISSUE THREAD

**Issue by allisonmarie0127** [SingleTact/StandaloneArduino#5]
Hi there!

I am trying to implement the standalone arduino code with multiple sensors, a multiplexer, and an Arduino Uno Rev2 Wifi. I have more than just force sensors on this project, where one group of sensors are on one channel, another on a different channel, and so on. I have the force sensors connected to channel 5 of my mux, and have set different addresses for each of the force sensors, so they can each be called.

I was thinking this would be relatively easy to implement with the standalone arduino code, by just including the I2CMux.h and switching to channel 5. However, with a mux present, I keep getting error code 3 of wire.endTransmission. Apparently no ack is being sent by the sensors, so the error returns a -1 instead. I've tried resolving the issues multiple ways, but nothing seems to be working. Is there something missing in this code that would cause this?

Thanks!

**Comment by dayizhang** [comment]
Make sure you have the right pull-up, i2c clock and clock stretching support on your mux,
